# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e1c5f310079b804582a6ebd1538de295472e1e6650ccfc03bc62739bd06a1b8ea6bf5732ee4f0543c493cb8d1f9bc724e857ba1469bb117d7b7fe1861890842

test:
  secret_key_base: cbf3486196cc4ef0f3ffc4c2c7f7daca7edebe81c7aa723a75ebdf368259711ef996a25027002ea3ff38929fe6eed6de25de515b09dc73911f85fe562e6ae20b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
